#!/bin/bash
# xmonad session script
# This file is executed during xmonad startup by /usr/bin/xmonad-start script
# as packaged by Fedora (similar to how ~/.xprofile used to work).

# debug mode
if [[ $1 = "-d" ]]; then
  DEBUG=echo
  shift
else
  unset DEBUG
fi

# set keyboard layout
$DEBUG setxkbmap us -variant cz_sk_de

# force reload of custom X configuration
$DEBUG xrdb -merge ~/.Xresources

# make ctr-atl-backspace work again
# $DEBUG setxkbmap -option terminate:ctrl_alt_bksp

# remap some keys
# $DEBUG xmodmap ~/.xmodmaprc

# run screensaver
$DEBUG xscreensaver -no-splash &

# configure monitor via xrandr
if [[ -f xrandr.sh ]]; then
  source xrandr.sh
fi

# set wallpaper
wallpaper=~/data/wallpapers/wallpaper.jpg
$DEBUG xloadimage -onroot -fullscreen -background black -center "${wallpaper}"
