#!/bin/bash

#
# example of ~/.xprofile file for xmonad session
#

# set wallpaper
wallpaper=~/data/wallpapers/dark-fedora-wallpaper.jpg
xloadimage -onroot -fullscreen -background black -center "${wallpaper}"

# set keyboard layout
setxkbmap us -variant cz_sk_de

# force reload of custom X configuration
xrdb -merge ~/.Xresources

# make ctr-atl-backspace work again
# setxkbmap -option terminate:ctrl_alt_bksp

# remap some keys
# xmodmap ~/.xmodmaprc

# run screensaver
xscreensaver -no-splash &
